#!/usr/bin/env bash
set -ex
pip install microscopy-analysis-pipeline/

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u "run_pipeline.py"
